org.gradle.jvmargs=-Xmx3G

minecraft_version=1.20.6

archives_base_name=RemoteResourcePack
mod_version=1.2.7+1.21
maven_group=xland.mcmod

#architectury_version=4.11.93

fabric_loader_version=0.14.22
#fabric_api_version=0.76.0+1.18.2

lexforge_version=1.20.6-50.1.7
neoforge_version=20.6.119
use_neo_gradle=false

mr_project_id=ic0PN6f8
mr_version_display=1.2.7
mr_version_mod_abbr=RRP
mr_version_game_range=1.21.1-1.20.5
# 1: MC version range, 2: loader name, 3: mod abbreviation 4: version displayed
mr_version_name_format=[%1$s %2$s] %4$s
mr_version_changelog=Remove forgefix
mr_version_type=beta
mr_version_game=1.21.1,1.21,1.20.6,1.20.5

