org.gradle.jvmargs=-Xmx3G

minecraft_version=26.1-snapshot-1

archives_base_name=RemoteResourcePack
mod_version=2.2.3+26.1
maven_group=xland.mcmod

fabric_loader_version=0.18.4

#lexforge_version=1.21.10-60.0.5
neoforge_version=26.1.0.0-alpha.2+snapshot-1
neoform_version=26.1-snapshot-1-3

mr_project_id=ic0PN6f8
mr_version_display=2.2.3
mr_version_mod_abbr=RRP
mr_version_game_range=26.1-snap
# 1: MC version range, 2: loader name, 3: mod abbreviation 4: version displayed
mr_version_name_format=[%1$s %2$s] %4$s
mr_version_changelog=Update icon
mr_version_type=beta
mr_version_game=26.1-snapshot-1

