org.gradle.jvmargs=-Xmx2G

minecraft_version=26.1

archives_base_name=RemoteResourcePack
mod_version=2.2.5+26.1
maven_group=xland.mcmod

fabric_loader_version=0.18.4

#lexforge_version=1.21.10-60.0.5
neoforge_version=26.1.0.1-beta
neoform_version=26.1-1

mr_project_id=ic0PN6f8
mr_loaders=fabric,neoforge,forge
mr_version_display=2.2.5
mr_version_mod_abbr=RRP
mr_version_game_range=26.1
# 1: MC version range, 2: loader name, 3: mod abbreviation 4: version displayed
mr_version_name_format=[%1$s %2$s] %4$s
mr_version_changelog=Support 26.1.\n\nUnder MCForge environment, you can \
  disable the Neo Migration screen by creating a file named `rrp-neo-migration-screen.disable`\
  under the `config` folder.
# release, beta, alpha
mr_version_type=release
mr_version_game=26.1

