# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "remoteresourcepack"
mod.name = "Remote Resource Pack"
mod.group = "xland.mcmod"
mod.version = "3.0.0-beta.6"

deps.fabric_loader = "0.19.3"
loomx.loom_version = "1.17-SNAPSHOT"


["1.20.1"]
mod.mc_releases = ["1.20", "1.20.1"]
mod.mc_releases_display = "1.20.1"

[fabric."1.20.1"]
mod.mc_compat = ">=1.20- <=1.20.1"
deps.fabric_api = "0.92.9+1.20.1"

[forge."1.20.1"]
mod.mc_compat = "[1.20, 1.20.1]"
deps.forge = "1.20.1-47.4.20"


["1.21.1"]
# List of releases to be marked compatible on Modrinth/Curseforge
mod.mc_releases = ["1.21", "1.21.1"]
mod.mc_releases_display = "1.21.1"

[fabric."1.21.1"]
# Mod compatibility range in fabric.mod.json/neoforge.mods.toml
mod.mc_compat = ">=1.21- <=1.21.1"
deps.fabric_api = "0.116.13+1.21.1"

[neoforge."1.21.1"]
mod.mc_compat = "[1.21, 1.21.1]"
deps.neo_loader = "21.1.234"

[forge."1.21.1"]
mod.mc_compat = "[1.21, 1.21.1]"
deps.forge = "1.21.1-52.1.0"


["1.21.11"]
mod.mc_releases = ["1.21.11"]
mod.mc_releases_display = "1.21.11"

[fabric."1.21.11"]
mod.mc_compat = ">1.21.10 <2"
deps.fabric_api = "0.141.4+1.21.11"

[neoforge."1.21.11"]
mod.mc_compat = "[1.21.11]"
deps.neo_loader = "21.11.42"

[forge."1.21.11"]
mod.mc_compat = "[1.21.11]"
deps.forge = "1.21.11-61.1.0"


["26.2.x"]
mod.mc_releases = ["26.1", "26.1.1", "26.1.2", "26.2"]
mod.mc_releases_display = "26.1+"

[fabric."26.2.x"]
mod.mc_compat = ">=26.1-"
deps.fabric_api = "0.153.0+26.2"

[neoforge."26.2.x"]
mod.mc_compat = "[26.1,)"
deps.neo_loader = "26.2.0.7-beta"

[forge."26.2.x"]
mod.mc_compat = "[26.1,)"
deps.forge = "26.2-65.0.3"
